global h L1
L1 = imread('cameraman.tif');
L1 = double(L1) / 255;
figure;
h(1) = imshow(L1);

h(2) = uicontrol('Style', 'slider', ...
    'units', 'normalized', ...
    'Min', .1, 'Max', 1, 'Value', .1, ...
    'Position', [.05, .08, .9, .05], ... % x, y position; x, y size (in%)
    'Callback', 'f1');

h(3) = uicontrol('Style', 'slider', ...
    'units', 'normalized', ...
    'Min', -45, 'Max', 45, 'Value', 0, ...
    'Position', [.05, .01, .9, .05], ...
    'Callback', 'f1');

h(4) = uicontrol('Style', 'popup', ...
    'String', {'gray', 'jet', 'hsv', 'prism', 'hot'}, ...
    'units', 'normalized', ...
    'Position', [.8, .9, .15, .1], ...
    'Callback', 'f1');

f1; % apply slider value - 10% blur at start
