global h L1 L2
PATH = "FOLDER_PATH";

L1 = imread('cameraman.tif');
L2 = imread(PATH+"\flowers-fhd.jpg");
L1 = double(L1) / 255;
L2 = double(L2) / 255;
L1 = cat(3, L1, L1, L1);
figure;
h(1) = imshow(L2);

h(2) = uicontrol('Style', 'checkbox', ...
    'units', 'normalized', ...
    'Position', [.01, .95, .04, .03], ...
    'String', 'gray', ...
    'Value', 0, ...
    'Callback', 'f1(1)');

h(3) = uicontrol('Style', 'checkbox', ...
    'units', 'normalized', ...
    'Position', [.01, .9, .04, .03], ...
    'String', 'RGB', ...
    'Value', 1, ...
    'Callback', 'f1(2)');

h(4) = uicontrol('Style', 'popup', ...
    'String', {'original', 's0', 's45', 's90', 's135', 'l', 'm19', 'm29', 'u19', 'u29'}, ...
    'units', 'normalized', ...
    'Position', [.9, .9, .09, .09], ...
    'Callback', 'f1(3)');

f1(2);
