global h L1

PATH = "FOLDER_PATH";
L1 = imread(PATH+"\flowers-fhd.jpg");
L1 = double(L1) / 255;
figure;

h(1) = imshow(L1);

h(2) = uicontrol('Style', 'slider', ...
    'units', 'normalized', ...
    'Min', -1, 'Max', 1, 'Value', 0, ...
    'Position', [.1, .11, .8, .05], ...
    'Callback', 'f1');

h(3) = uicontrol('Style', 'slider', ...
    'units', 'normalized', ...
    'Min', -1, 'Max', 1, 'Value', 0, ...
    'Position', [.1, .06, .8, .05], ...
    'Callback', 'f1');

h(4) = uicontrol('Style', 'slider', ...
    'units', 'normalized', ...
    'Min', -1, 'Max', 1, 'Value', 0, ...
    'Position', [.1, .01, .8, .05], ...
    'Callback', 'f1');

f1;